In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as snb
from scipy import stats
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [3]:
#Phase 1: Data Acquisition
#Here i am loading the data in to the python

In [4]:
dataset1 = pd.read_excel(r"C:\Users\Dell\Desktop\dataset_1.xlsx")

In [5]:
dataset1

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
0,1,2011-01-01,1,0,1,0,False,6,1,0.24
1,2,2011-01-01,1,0,1,1,False,6,1,0.22
2,3,2011-01-01,1,0,1,2,False,6,1,0.22
3,4,2011-01-01,1,0,1,3,False,6,1,0.24
4,5,2011-01-01,1,0,1,4,False,6,1,0.24
...,...,...,...,...,...,...,...,...,...,...
605,606,2011-01-28,1,0,1,11,False,5,3,0.18
606,607,2011-01-28,1,0,1,12,False,5,3,0.18
607,608,2011-01-28,1,0,1,13,False,5,3,0.18
608,609,2011-01-28,1,0,1,14,False,5,3,0.22
609,610,2011-01-28,1,0,1,15,False,5,2,0.20

In [6]:
#info means it returns all information about the dataframe

In [7]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     610 non-null    int64
 1   dteday      610 non-null    datetime64[ns]
 2   season      610 non-null    int64
 3   yr          610 non-null    int64
 4   mnth        610 non-null    int64
 5   hr          610 non-null    int64
 6   holiday     610 non-null    bool
 7   weekday     610 non-null    int64
 8   weathersit  610 non-null    int64
 9   temp        610 non-null    float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(7)
memory usage: 43.6 KB

In [8]:
# isnull() means it returns null value of the dataframe

In [9]:
dataset1.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [10]:
# duplicate means it returns duplicate value of the dataframe

In [11]:
dataset1.duplicated().sum()

0

In [12]:
# describe() means it returns numeric value of the dataframe

In [13]:
dataset1.describe()

,instant,dteday,season,yr,mnth,hr,weekday,weathersit,temp
count,610.000000,610,610.0,610.0,610.0,610.000000,610.000000,610.000000,610.000000
mean,305.500000,2011-01-13 19:47:24.590163968,1.0,0.0,1.0,11.795082,2.977049,1.477049,0.196885
min,1.000000,2011-01-01 00:00:00,1.0,0.0,1.0,0.000000,0.000000,1.000000,0.020000
25%,153.250000,2011-01-07 00:00:00,1.0,0.0,1.0,6.000000,1.000000,1.000000,0.160000
50%,305.500000,2011-01-14 00:00:00,1.0,0.0,1.0,12.000000,3.000000,1.000000,0.200000
75%,457.750000,2011-01-21 00:00:00,1.0,0.0,1.0,18.000000,5.000000,2.000000,0.235000
max,610.000000,2011-01-28 00:00:00,1.0,0.0,1.0,23.000000,6.000000,4.000000,0.460000
std,176.236111,NaN,0.0,0.0,0.0,6.852107,2.054943,0.643496,0.081304

In [14]:
#Here i am deleting the 'yr' column and rename some columns in the data set
#We have deleted this because the some column spelling was incorrect
#While deleting the column, we can also use'inplace=true'but it is for permanent deletion

In [15]:
df1 = dataset1.drop(columns=['yr'], axis=1).rename(columns = {'mnth':'month',
                          'hr':'hour','dteday':'dateday'})

In [16]:
df1

,instant,dateday,season,month,hour,holiday,weekday,weathersit,temp
0,1,2011-01-01,1,1,0,False,6,1,0.24
1,2,2011-01-01,1,1,1,False,6,1,0.22
2,3,2011-01-01,1,1,2,False,6,1,0.22
3,4,2011-01-01,1,1,3,False,6,1,0.24
4,5,2011-01-01,1,1,4,False,6,1,0.24
...,...,...,...,...,...,...,...,...,...
605,606,2011-01-28,1,1,11,False,5,3,0.18
606,607,2011-01-28,1,1,12,False,5,3,0.18
607,608,2011-01-28,1,1,13,False,5,3,0.18
608,609,2011-01-28,1,1,14,False,5,3,0.22
609,610,2011-01-28,1,1,15,False,5,2,0.20

In [17]:
# head() means it returns top 5 records of the dataframe
#head() bydefault returns top 5 values. If we want more than 5 values then we can pass in head(50) function

In [18]:
df1.head()

   instant    dateday  season  month  hour  holiday  weekday  weathersit  temp
0        1 2011-01-01       1      1     0    False        6           1  0.24
1        2 2011-01-01       1      1     1    False        6           1  0.22
2        3 2011-01-01       1      1     2    False        6           1  0.22
3        4 2011-01-01       1      1     3    False        6           1  0.24
4        5 2011-01-01       1      1     4    False        6           1  0.24

In [19]:
 # tail() means it returns down 5 records of the dataframe
#tail() bydefault returns down 5 values. If we want more than 5 values then we can pass in tail(20) function

In [20]:
df1.tail()

,instant,dateday,season,month,hour,holiday,weekday,weathersit,temp
605,606,2011-01-28,1,1,11,False,5,3,0.18
606,607,2011-01-28,1,1,12,False,5,3,0.18
607,608,2011-01-28,1,1,13,False,5,3,0.18
608,609,2011-01-28,1,1,14,False,5,3,0.22
609,610,2011-01-28,1,1,15,False,5,2,0.20

In [21]:
df1.isnull().sum()

instant       0
dateday       0
season        0
month         0
hour          0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [22]:
df1.dtypes

instant                int64
dateday       datetime64[ns]
season                 int64
month                  int64
hour                   int64
holiday                 bool
weekday                int64
weathersit             int64
temp                 float64
dtype: object

In [23]:
df1.columns

Index(['instant', 'dateday', 'season', 'month', 'hour', 'holiday', 'weekday',
       'weathersit', 'temp'],
      dtype='object')

In [24]:
#Here i am loading the dataset2 in to the python

In [25]:
dataset2 = pd.read_excel(r"C:\Users\Dell\Desktop\dataset_2.xlsx")

In [26]:
dataset2

     Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]

In [27]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  610 non-null    int64
 1   instant     610 non-null    int64
 2   atemp       599 non-null    float64
 3   hum         610 non-null    float64
 4   windspeed   610 non-null    float64
 5   casual      610 non-null    int64
 6   registered  610 non-null    int64
 7   cnt         610 non-null    int64
dtypes: float64(3), int64(5)
memory usage: 38.3 KB

In [28]:
#Here i am checking the datatypes in to the dataset

In [29]:
dataset2.dtypes

Unnamed: 0      int64
instant         int64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [30]:
dataset2.isnull().sum()

Unnamed: 0     0
instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

In [31]:
dataset2.head(20)

    Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0            0        1  0.2879  0.81     0.0000       3          13   16
1            1        2  0.2727  0.80     0.0000       8          32   40
2            2        3  0.2727  0.80     0.0000       5          27   32
3            3        4  0.2879  0.75     0.0000       3          10   13
4            4        5  0.2879  0.75     0.0000       0           1    1
5            5        6  0.2576  0.75     0.0896       0           1    1
6            6        7  0.2727  0.80     0.0000       2           0    2
7            7        8  0.2576  0.86     0.0000       1           2    3
8            8        9     NaN  0.75     0.0000       1           7    8
9            9       10  0.3485  0.76     0.0000       8           6   14
10          10       11  0.3939  0.76     0.2537      12          24   36
11          11       12  0.3333  0.81     0.2836      26          30   56
12          12       13  0.4242  0.77     0.2836      29          55   84
13          13       14  0.4545  0.72     0.2985      47          47   94
14          14       15  0.4545  0.72     0.2836      35          71  106
15          15       16  0.4394  0.77     0.2985      40          70  110
16          16       17  0.4242  0.82     0.2985      41          52   93
17          17       18     NaN  0.82     0.2836      15          52   67
18          18       19  0.4242  0.88     0.2537       9          26   35
19          19       20  0.4242  0.88     0.2537       6          31   37

In [32]:
#here i am the fill nullvalue by the median() function Because we got NULL values in the atemp column
#Here we have calculated the median value of the 'atemp' column name and then replaced that value with 'Nan'(means null value)

In [33]:
dataset2["atemp"].median()

0.197

In [34]:
dataset2["atemp"] = dataset2["atemp"].replace(np.nan,0.197)

In [35]:
dataset2.head(20)

    Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0            0        1  0.2879  0.81     0.0000       3          13   16
1            1        2  0.2727  0.80     0.0000       8          32   40
2            2        3  0.2727  0.80     0.0000       5          27   32
3            3        4  0.2879  0.75     0.0000       3          10   13
4            4        5  0.2879  0.75     0.0000       0           1    1
5            5        6  0.2576  0.75     0.0896       0           1    1
6            6        7  0.2727  0.80     0.0000       2           0    2
7            7        8  0.2576  0.86     0.0000       1           2    3
8            8        9  0.1970  0.75     0.0000       1           7    8
9            9       10  0.3485  0.76     0.0000       8           6   14
10          10       11  0.3939  0.76     0.2537      12          24   36
11          11       12  0.3333  0.81     0.2836      26          30   56
12          12       13  0.4242  0.77     0.2836      29          55   84
13          13       14  0.4545  0.72     0.2985      47          47   94
14          14       15  0.4545  0.72     0.2836      35          71  106
15          15       16  0.4394  0.77     0.2985      40          70  110
16          16       17  0.4242  0.82     0.2985      41          52   93
17          17       18  0.1970  0.82     0.2836      15          52   67
18          18       19  0.4242  0.88     0.2537       9          26   35
19          19       20  0.4242  0.88     0.2537       6          31   37

In [36]:
dataset2.tail(20)

     Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
590         590      591  0.2273  0.69     0.0896       3          76   79
591         591      592  0.2121  0.74     0.0896       4          55   59
592         592      593  0.2121  0.74     0.0896       2          36   38
593         593      594  0.2121  0.74     0.0896       0          27   27
594         594      595  0.1970  0.80     0.1642       0          16   16
595         595      596  0.2121  0.75     0.1343       0           9    9
596         596      597  0.2121  0.75     0.1343       1           2    3
597         597      598  0.2121  0.75     0.1642       0           2    2
598         598      599  0.2273  0.75     0.1045       1           0    1
599         599      600  0.2121  0.80     0.1045       0           4    4
600         600      601  0.1970  0.80     0.1343       0          16   16
601         601      602  0.1970  0.86     0.0896       2          58   60
602         602      603  0.1970  0.86     0.0896       2         155  157
603         603      604  0.2121  0.86     0.0896       6          95  101
604         604      605  0.2121  0.86     0.1045       0          49   49
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

In [37]:
dataset2.isnull().sum()

Unnamed: 0    0
instant       0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [38]:
#here i am deleting the 'Unnamed: 0' column and rename some columns in the data set
#We have correct spelling of the some column spelling was incorrect
#While deleting the column, we can also use'inplace=true'but it is for permanent deletion

In [39]:
df2 = dataset2.drop(columns=['Unnamed: 0'], axis=1).rename(columns = {'hum':'humidity',
                          'cnt':'count'})

In [40]:
df2

     instant   atemp  humidity  windspeed  casual  registered  count
0          1  0.2879      0.81     0.0000       3          13     16
1          2  0.2727      0.80     0.0000       8          32     40
2          3  0.2727      0.80     0.0000       5          27     32
3          4  0.2879      0.75     0.0000       3          10     13
4          5  0.2879      0.75     0.0000       0           1      1
..       ...     ...       ...        ...     ...         ...    ...
605      606  0.2121      0.93     0.1045       0          30     30
606      607  0.2121      0.93     0.1045       1          28     29
607      608  0.2121      0.93     0.1045       0          31     31
608      609  0.2727      0.80     0.0000       2          36     38
609      610  0.2576      0.86     0.0000       1          40     41

[610 rows x 7 columns]

In [41]:
df2.isnull().sum()

instant       0
atemp         0
humidity      0
windspeed     0
casual        0
registered    0
count         0
dtype: int64

In [42]:
df2.columns

Index(['instant', 'atemp', 'humidity', 'windspeed', 'casual', 'registered',
       'count'],
      dtype='object')

In [43]:
df2.dtypes

instant         int64
atemp         float64
humidity      float64
windspeed     float64
casual          int64
registered      int64
count           int64
dtype: object

In [44]:
df2.duplicated().sum()

0

In [45]:
df2.describe()

,instant,atemp,humidity,windspeed,casual,registered,count
count,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000
mean,305.500000,0.199882,0.562475,0.204851,4.501639,51.068852,55.570492
std,176.236111,0.078121,0.175440,0.121806,6.319945,47.021204,49.316802
min,1.000000,0.000000,0.210000,0.000000,0.000000,0.000000,1.000000
25%,153.250000,0.151500,0.432500,0.104500,0.000000,14.000000,16.000000
50%,305.500000,0.197000,0.520000,0.194000,2.000000,43.000000,47.000000
75%,457.750000,0.227300,0.690000,0.283600,6.000000,70.000000,79.750000
max,610.000000,0.454500,1.000000,0.582100,47.000000,247.000000,249.000000

Dataset_1 and Dataset_2 Integration

In [46]:
# here merge the data after cleanning data1&2

In [47]:
merge_data = pd.merge(df1,df2,on='instant',how ='inner')

In [48]:
merge_data

,instant,dateday,season,month,hour,holiday,weekday,weathersit,temp,atemp,humidity,windspeed,casual,registered,count
0,1,2011-01-01,1,1,0,False,6,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,1,1,False,6,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,1,2,False,6,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,1,3,False,6,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,1,4,False,6,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,606,2011-01-28,1,1,11,False,5,3,0.18,0.2121,0.93,0.1045,0,30,30
606,607,2011-01-28,1,1,12,False,5,3,0.18,0.2121,0.93,0.1045,1,28,29
607,608,2011-01-28,1,1,13,False,5,3,0.18,0.2121,0.93,0.1045,0,31,31
608,609,2011-01-28,1,1,14,False,5,3,0.22,0.2727,0.80,0.0000,2,36,38
609,610,2011-01-28,1,1,15,False,5,2,0.20,0.2576,0.86,0.0000,1,40,41

In [49]:
merge_data.describe()

,instant,dateday,season,month,hour,weekday,weathersit,temp,atemp,humidity,windspeed,casual,registered,count
count,610.000000,610,610.0,610.0,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000
mean,305.500000,2011-01-13 19:47:24.590163968,1.0,1.0,11.795082,2.977049,1.477049,0.196885,0.199882,0.562475,0.204851,4.501639,51.068852,55.570492
min,1.000000,2011-01-01 00:00:00,1.0,1.0,0.000000,0.000000,1.000000,0.020000,0.000000,0.210000,0.000000,0.000000,0.000000,1.000000
25%,153.250000,2011-01-07 00:00:00,1.0,1.0,6.000000,1.000000,1.000000,0.160000,0.151500,0.432500,0.104500,0.000000,14.000000,16.000000
50%,305.500000,2011-01-14 00:00:00,1.0,1.0,12.000000,3.000000,1.000000,0.200000,0.197000,0.520000,0.194000,2.000000,43.000000,47.000000
75%,457.750000,2011-01-21 00:00:00,1.0,1.0,18.000000,5.000000,2.000000,0.235000,0.227300,0.690000,0.283600,6.000000,70.000000,79.750000
max,610.000000,2011-01-28 00:00:00,1.0,1.0,23.000000,6.000000,4.000000,0.460000,0.454500,1.000000,0.582100,47.000000,247.000000,249.000000
std,176.236111,NaN,0.0,0.0,6.852107,2.054943,0.643496,0.081304,0.078121,0.175440,0.121806,6.319945,47.021204,49.316802

In [50]:
merge_data.isnull().sum()

instant       0
dateday       0
season        0
month         0
hour          0
holiday       0
weekday       0
weathersit    0
temp          0
atemp         0
humidity      0
windspeed     0
casual        0
registered    0
count         0
dtype: int64

In [51]:
merge_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     610 non-null    int64
 1   dateday     610 non-null    datetime64[ns]
 2   season      610 non-null    int64
 3   month       610 non-null    int64
 4   hour        610 non-null    int64
 5   holiday     610 non-null    bool
 6   weekday     610 non-null    int64
 7   weathersit  610 non-null    int64
 8   temp        610 non-null    float64
 9   atemp       610 non-null    float64
 10  humidity    610 non-null    float64
 11  windspeed   610 non-null    float64
 12  casual      610 non-null    int64
 13  registered  610 non-null    int64
 14  count       610 non-null    int64
dtypes: bool(1), datetime64[ns](1), float64(4), int64(9)
memory usage: 67.4 KB

In [52]:
merge_data.duplicated().sum()

0

In [53]:
#Here i am loading the dataset3 in to the python

In [54]:
dataset3 = pd.read_excel(r"C:\Users\Dell\Desktop\dataset_3.xlsx")

In [55]:
dataset3

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,620,2011-01-29,1,0,1,1,False,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,621,2011-01-29,1,0,1,2,False,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,622,2011-01-29,1,0,1,3,False,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,623,2011-01-29,1,0,1,4,False,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,624,2011-01-29,1,0,1,6,False,6,1,0.16,0.1818,0.64,0.1343,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,615,2011-01-28,1,0,1,20,False,5,2,0.24,0.2273,0.70,0.1940,1,61,62
386,616,2011-01-28,1,0,1,21,False,5,2,0.22,0.2273,0.75,0.1343,1,57,58
387,617,2011-01-28,1,0,1,22,False,5,1,0.24,0.2121,0.65,0.3582,0,26,26
388,618,2011-01-28,1,0,1,23,False,5,1,0.24,0.2273,0.60,0.2239,1,22,23
389,619,2011-01-29,1,0,1,0,False,6,1,0.22,0.1970,0.64,0.3582,2,26,28

In [56]:
dataset3.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [57]:
dataset3.duplicated().sum()

0

In [58]:
df3 = dataset3.drop(columns=['yr'], axis=1).rename(columns = {'mnth':'month',
                          'hr':'hour','dteday':'dateday','cnt':'count','hum':'humidity'})

In [59]:
df3

,instant,dateday,season,month,hour,holiday,weekday,weathersit,temp,atemp,humidity,windspeed,casual,registered,count
0,620,2011-01-29,1,1,1,False,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,621,2011-01-29,1,1,2,False,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,622,2011-01-29,1,1,3,False,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,623,2011-01-29,1,1,4,False,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,624,2011-01-29,1,1,6,False,6,1,0.16,0.1818,0.64,0.1343,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,615,2011-01-28,1,1,20,False,5,2,0.24,0.2273,0.70,0.1940,1,61,62
386,616,2011-01-28,1,1,21,False,5,2,0.22,0.2273,0.75,0.1343,1,57,58
387,617,2011-01-28,1,1,22,False,5,1,0.24,0.2121,0.65,0.3582,0,26,26
388,618,2011-01-28,1,1,23,False,5,1,0.24,0.2273,0.60,0.2239,1,22,23
389,619,2011-01-29,1,1,0,False,6,1,0.22,0.1970,0.64,0.3582,2,26,28

In [60]:
merge_data.columns

Index(['instant', 'dateday', 'season', 'month', 'hour', 'holiday', 'weekday',
       'weathersit', 'temp', 'atemp', 'humidity', 'windspeed', 'casual',
       'registered', 'count'],
      dtype='object')

In [61]:
df3.columns

Index(['instant', 'dateday', 'season', 'month', 'hour', 'holiday', 'weekday',
       'weathersit', 'temp', 'atemp', 'humidity', 'windspeed', 'casual',
       'registered', 'count'],
      dtype='object')

In [62]:
# here concatenate the data after cleanning merge_data&dataset3

In [63]:
final_data = pd.concat([merge_data,df3],ignore_index=True,sort=False, keys=['x','y'])

In [64]:
final_data

,instant,dateday,season,month,hour,holiday,weekday,weathersit,temp,atemp,humidity,windspeed,casual,registered,count
0,1,2011-01-01,1,1,0,False,6,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,1,1,False,6,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,1,2,False,6,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,1,3,False,6,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,1,4,False,6,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,615,2011-01-28,1,1,20,False,5,2,0.24,0.2273,0.70,0.1940,1,61,62
996,616,2011-01-28,1,1,21,False,5,2,0.22,0.2273,0.75,0.1343,1,57,58
997,617,2011-01-28,1,1,22,False,5,1,0.24,0.2121,0.65,0.3582,0,26,26
998,618,2011-01-28,1,1,23,False,5,1,0.24,0.2273,0.60,0.2239,1,22,23
999,619,2011-01-29,1,1,0,False,6,1,0.22,0.1970,0.64,0.3582,2,26,28

In [65]:
final_data.isnull().sum()

instant       0
dateday       0
season        0
month         0
hour          0
holiday       0
weekday       0
weathersit    0
temp          0
atemp         0
humidity      0
windspeed     0
casual        0
registered    0
count         0
dtype: int64

In [66]:
final_data.duplicated().sum()

0

In [67]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     1000 non-null   int64
 1   dateday     1000 non-null   datetime64[ns]
 2   season      1000 non-null   int64
 3   month       1000 non-null   int64
 4   hour        1000 non-null   int64
 5   holiday     1000 non-null   bool
 6   weekday     1000 non-null   int64
 7   weathersit  1000 non-null   int64
 8   temp        1000 non-null   float64
 9   atemp       1000 non-null   float64
 10  humidity    1000 non-null   float64
 11  windspeed   1000 non-null   float64
 12  casual      1000 non-null   int64
 13  registered  1000 non-null   int64
 14  count       1000 non-null   int64
dtypes: bool(1), datetime64[ns](1), float64(4), int64(9)
memory usage: 110.5 KB

In [68]:
final_data.describe()

,instant,dateday,season,month,hour,weekday,weathersit,temp,atemp,humidity,windspeed,casual,registered,count
count,1000.000000,1000,1000.0,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,2011-01-22 15:56:09.600000,1.0,1.312000,11.753000,2.982000,1.480000,0.205900,0.211793,0.582480,0.194931,4.921000,53.383000,58.304000
min,1.000000,2011-01-01 00:00:00,1.0,1.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.210000,0.000000,0.000000,0.000000,1.000000
25%,250.750000,2011-01-11 00:00:00,1.0,1.000000,6.000000,1.000000,1.000000,0.160000,0.166700,0.440000,0.104500,0.000000,15.000000,16.000000
50%,500.500000,2011-01-22 00:00:00,1.0,1.000000,12.000000,3.000000,1.000000,0.200000,0.212100,0.550000,0.164200,3.000000,46.000000,49.000000
75%,750.250000,2011-02-03 00:00:00,1.0,2.000000,18.000000,5.000000,2.000000,0.240000,0.257600,0.700000,0.283600,6.000000,74.000000,83.000000
max,1000.000000,2011-02-14 00:00:00,1.0,2.000000,23.000000,6.000000,4.000000,0.460000,0.454500,1.000000,0.582100,62.000000,247.000000,249.000000
std,288.819436,NaN,0.0,0.463542,6.899101,2.091423,0.651171,0.078977,0.076295,0.187977,0.129126,7.643899,47.893968,50.985558

In [70]:
final_data

,instant,dateday,season,month,hour,holiday,weekday,weathersit,temp,atemp,humidity,windspeed,casual,registered,count
0,1,2011-01-01,1,1,0,False,6,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,1,1,False,6,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,1,2,False,6,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,1,3,False,6,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,1,4,False,6,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,615,2011-01-28,1,1,20,False,5,2,0.24,0.2273,0.70,0.1940,1,61,62
996,616,2011-01-28,1,1,21,False,5,2,0.22,0.2273,0.75,0.1343,1,57,58
997,617,2011-01-28,1,1,22,False,5,1,0.24,0.2121,0.65,0.3582,0,26,26
998,618,2011-01-28,1,1,23,False,5,1,0.24,0.2273,0.60,0.2239,1,22,23
999,619,2011-01-29,1,1,0,False,6,1,0.22,0.1970,0.64,0.3582,2,26,28

In [ ]:
#here i am get the final data By using this function we will get the final data.

In [71]:
final_data.to_csv('final-data.csv', index=False)